// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCustomer = "customers"

// Customer mapped from table <customers>
type Customer struct {
	ID    string `gorm:"column:id;primaryKey" json:"id"`
	Name  string `gorm:"column:name;not null" json:"name"`
	Email string `gorm:"column:email;not null" json:"email"`
	Phone string `gorm:"column:phone;not null" json:"phone"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
