// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	OrderDate  time.Time `gorm:"column:orderDate;not null" json:"orderDate"`
	Amount     float64   `gorm:"column:amount;not null" json:"amount"`
	CustomerID string    `gorm:"column:customerId;not null" json:"customerId"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
